PI_CMD_TRANSIT_WAYPOINTS = 0x01
PI_CMD_ROTATE_AND_DRIVE  = 0x02
PI_CMD_SET_BOT_OPTION    = 0x03
PI_CMD_FIND_OBJECT       = 0x04

PI_OPTION_FOLLOW_ME_MODE = 0x01

BOT_OPTION_CALIBRATE            = 0xB0
BOT_OPTION_RESET_TO_ORIGIN      = 0xB1
BOT_OPTION_SET_PID_PARAMETERS   = 0xB2